#!/usr/bin/env bash
#
# Developed by Anya Harter <aharter@redhat.com> on 2018-08-03
# With help from Kevin Postlethwait <kpostlet@redhat.com>
#
# Pass in the Test-cockpit-<test-file-name>-results-<date>.log file
#

tabs 11 17 57

echo "-----------------------------------------------------------------"
printf " \033[1;37mSTATUS\t #\tNAME\tDURATION\033[1;000m\n"
echo "-----------------------------------------------------------------"

gawk '{gsub(/not ok/,"\033[0;31m FAILURE  \033[1;000m")}{gsub(/\<ok\>/,"\033[0;32m SUCCESS  \033[1;000m")}{gsub(/__main__/,"")}{gsub("\\.","")}{gsub("[0-9]+ ","&\t")}{gsub("# duration: ","\t")}/FAILURE|SUCCESS/' $1

testsfailed=`gawk '{gsub("#","\033[0;33m")}{gsub("]","&\033[1;000m")}/FAILED/' $1`
testspassed=`gawk '{gsub("#","\033[0;33m")}{gsub("]","&\033[1;000m")}/PASSED/' $1`

if ! [ -z "$testsfailed" ]
then
    echo "-----------------------------------------------------------------"
    gawk '{gsub("# "," \033[7;31m")}{gsub("]","&\033[1;000m")}/FAILED/' $1
    echo "-----------------------------------------------------------------"
elif ! [ -z "$testspassed" ]
then 
    echo "-----------------------------------------------------------------"
    gawk '{gsub("# "," \033[7;32m")}{gsub("]","&\033[1;000m")}/PASSED/' $1
    echo "-----------------------------------------------------------------"
else
    echo "-----------------------------------------------------------------"
    echo -e " \033[7;33mTEST SUITE FAILED TO TERMINATE\033[1;000m"
    echo "-----------------------------------------------------------------"
fi

tabs 8
